#!/bin/sh

setxkbmap -layout "us,ru"

hsetroot -solid "#181825"

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config border_width 2
bspc config window_gap 10

bspc config bottom_padding 5
bspc config left_padding 5
bspc config right_padding 5
bspc config top_padding 5

bspc config active_border_color "#45475a"
bspc config focused_border_color "#cba6f7"
bspc config normal_border_color "#45475a"

~/.config/bspwm/scripts/setup_monitors.sh
~/.config/bspwm/scripts/setup_workspaces.sh
~/.config/bspwm/scripts/autostart.sh
